# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "android-12.1" branch
  push:
    branches: [ "android-12.1" ]
  pull_request:
    branches: [ "android-12.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

  Build_script:
      - ln -fs /usr/share/zoneinfo/Asia/Dhaka /etc/localtime && date
      - locale-gen en_US en_US.UTF-8
      - bash builder.sh
